config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'

  get 'profiles/show'
  get 'my_network/show'
  resources :friendships
  resources :likes
  devise_for :users
  resources :thoughts do 
    resources :comments
    member do 
      post 'like', to: 'likes#create'
    end
  end

   root 'thoughts#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :thoughts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  has_many :likes
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "40x40#", network: "200x200#" }, default_url: "http://placehold.it/40x40"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  
  def pending_requests
      self.friendships.where(:accepted => false)
  end

  def pending_requests_ids
      @array = self.pending_requests.pluck(:friend_id)
      @ids = []
      @ids << @array
      @pending_requests_ids = @ids.flatten
  end
  
  def recieved_requests
      self.inverse_friendships.where(:accepted => false)
  end

  def recieved_requests_ids
      @array = self.recieved_requests.pluck(:user_id)
      @ids = []
      @ids << @array
      @pending_requests_ids = @ids.flatten
  end
 
  def confirmed_friends
      @friends = []
      @friends << self.friendships.where(:accepted => true) 
      @friends << self.inverse_friendships.where(:accepted => true)
      @my_friends = @friends.flatten
  end
  
  def confirmed_friends_ids
      @friends = []
      @friends << self.friendships.where(:accepted => true).pluck(:friend_id) 
      @friends << self.inverse_friendships.where(:accepted => true).pluck(:user_id)
      @my_friends = @friends.flatten
  end

  def confirmed_profile_friendship(user_id, current_user)
    self.confirmed_friends.select do |x|
      if x["friend_id"] == user_id && x["user_id"] == current_user.id
        @friendship = x
      elsif x["user_id"] == user_id && x["friend_id"] == current_user.id
        @friendship = x
      end
    end
    return @friendship
  end
  
  def my_friends
    @active = self.friendships.pluck(:friend_id)
    @passive = self.inverse_friendships.pluck(:user_id)
    @the_ids = []
    @the_ids << @active
    @the_ids << @passive
    @my_friends = @the_ids.flatten
  end

  # Like methods
  def has_liked(thought_id)
    @likes = self.likes.pluck(:thought_id)
    if @likes.include?(thought_id)
      return true
    end
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  before_action :authenticate_user!
  
  def show
    @friend_ids = current_user.my_friends
    @user = User.find_by_id(params[:id])
    @thoughts = @user.thoughts.order('created_at DESC')
    @thought = current_user.thoughts.build
    @pending = current_user.friendships.where('friend_id= ?', @user.id)
    @recieved = current_user.inverse_friendships.where('user_id= ?', @user.id)
    @confirmed = current_user.confirmed_profile_friendship(@user.id, current_user)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_for @thought do |f| %>
    <% if @thought.errors.any? %>
        <ul>
          <% @thought.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
    <% end %>
    <div class='field'>
        <%= f.text_area :content, :class => "form-control", :rows => 3, :placeholder => "Whats on your mind?" %>
        <%= f.submit "post", :class => "btn btn-success" %>
    </div>
<% end %>

app/views/profiles/_profile.html.erb
<div class=" profile_wrapper text-center">
  <!-- Placeholder profile pic -->
  <%= image_tag @user.avatar.url(:medium) %>
  <!-- Profile details -->
  <h3><%= full_name(@user) %></h3>
  <h5 class="text-muted">Works as a <%= @user.occupation %>.</h5>
  <h5 class="text-muted">Lives in <%= @user.location %>.</h5>
  <hr>
  <h4>Bio</h4>
  <h5 class="text-muted"><%= @user.bio %></h5>
  <hr>
  <div class="button_wrapper">
     <div id="profile_button">
      <% if @user.id == current_user.id %>
        <%= link_to "Edit Profile", edit_user_registration_path(), :class => "btn btn-success" %>
      <% elsif @friend_ids.include?(@user.id) == false %>
        <%= link_to "Add Friend", friendships_path(:friend_id => @user.id), remote: true, :method => :post, :class => "btn btn-success" %>
      <% elsif current_user.pending_requests_ids.include?(@user.id) %>
        <% @pending.each do |friendship| %>
          <%= link_to "Cancel Request", friendship, :method => :delete, :class => "btn btn-warning" %>
        <% end %>
      <% elsif current_user.recieved_requests_ids.include?(@user.id) %>
        <% @recieved.each do |friendship| %>
          <%= form_for friendship, :url => {:controller => 'friendships', :action => 'update', :id => friendship.id }, :html => {method: :put} do |f| %>
            <%= f.submit "Accept", :class => "btn btn-success" %>
          <% end %>
        <% end %>    
      <% else %>
          <%= link_to "End Friendship", friendship_path( @confirmed, :friend_id => @user.id ), remote: true, :method => :delete, :class => "btn btn-warning" %> 
      <% end %>
    </div>
  </div>  
</div>

app/views/profiles/show.html.erb
<div class="row">
    <!-- Profile info partial -->
    <div class="col-sm-4">
        <%= render 'profile'%>
    </div>
    <!-- Users thoughts -->
     <div class="col-sm-8" id="profile_thoughts_loop">
         <div class="text-center">
             <h2><%= @user.first_name.capitalize %>'s Thoughts</h2>
         </div>
         <% if @user.id == current_user.id %>
             <div>
                 <%= render "form" %>
             </div>
         <% end %>
        <% @thoughts.each do |thought| %>
            <div class="thought_wrapper">
                <%= image_tag @user.avatar.url(:thumb), :class => "thought_avatar" %>
                <h4><%= link_to "#{ full_name(thought.user) }", profiles_show_path( :id => thought.user_id) %></h4>
                <p class="text-muted"><%= time_ago_in_words(thought.created_at) %> ago.</p>
                <div class="comment_counter">
                    <p><i class="fa fa-comment text-muted"></i>  <%= thought.comments.count %></p>
                </div>
                <hr>
                <div class="thought_content">
                    <p><%= thought.content %> </p>
                </div>
                <p>
                    <% if current_user.id == thought.user_id %>
                        <%= link_to "Edit", edit_thought_path(thought) %>
                        <%= link_to 'Destroy', thought_path(thought), method: :delete, data: {confirm: 'are you sure?'} %>
                    <% end %>
                </p>
                <hr>
                <div id="button_section_<%= thought.id %>">
                        <div id="button_section_content_<%= thought.id %>">
                            <div class="row">
                            <div class="col-sm-12">
                                <% if thought.likes.count > 0 %>
                                    <% if current_user.has_liked(thought.id) %>
                                        <% if thought.likes.count == 1 %>
                                            <p class="text-muted">You like this.</p>
                                        <% elsif thought.likes.count == 2 %>
                                            <p class="text-muted">You and 1 other person like this</p>
                                        <% elsif thought.likes.count > 2 %>
                                            <p class="text-muted">You and <%= thought.the_likes %> other people like this.</p>
                                        <% end %>
                                    <% else %>
                                        <% if thought.likes.count == 1 %>
                                            <p class="text-muted">1 person likes this.</p>
                                        <% elsif thought.likes.count > 1 %>
                                            <p class="text-muted"><%= thought.likes.count %> people like this.</p>
                                        <% end %>
                                    <% end %>
                                    <hr>
                                <% end %>
                            </div>
                        </div>
                        <!-- button group -->
                        <div class="row">
                            <div class="col-sm-12 text-center">
                                <div class="btn-group-justified" role="group">
                                    <div class="btn-group">
                                        <%= link_to thought_path(thought), :class => "btn btn-default thought_button" do %>
                                            <i class="fa fa-comment"></i> 
                                        <% end %>    
                                        </div>
                                        <div class="btn-group">
                                            <% if current_user.has_liked(thought.id) %>
                                                <div id="liked_icon_<%= thought.id %>">
                                                    <%= link_to like_path(thought, :thought_id => thought.id, :user_id => current_user.id ), remote: true, method: :delete, :class => "btn btn-default thought_button" do %>
                                                        <p><i class="fa fa-thumbs-o-up liked fa-lg"></i>  <%= thought.likes.count %></p>
                                                    <% end %>
                                                </div>
                                            <% else %>
                                                <div id="button_wrapper_<%= thought.id %>">
                                                    <%= link_to like_thought_path(thought), remote: true, method: :post, :class => "btn btn-default thought_button", :id => "unliked_thought_#{thought.id}" do %>
                                                        <p>
                                                            <i class="fa fa-thumbs-o-up"></i>
                                                             <% if thought.likes.count > 0 %>  
                                                                 <%= thought.likes.count %>
                                                             <% end %>
                                                        </p>
                                                    <% end %>
                                                </div>
                                            <% end %>    
                                        </div>
                                    </div><!-- end button group -->
                                </div><!-- end col(buttons) -->
                            </div><!-- end row(buttons) -->                            
                        </div>
                    </div>
            </div><!-- end thought wrapper -->
        <% end %><!-- end main thought loop -->
     </div><!-- end col-sm-8 -->
</div><!-- end row -->