config/routes.rb
Rails.application.routes.draw do
  get 'likes/create'

  get 'profiles/show'
  get 'my_network/show'
  resources :friendships
  resources :likes
  devise_for :users
  resources :thoughts do 
    resources :comments
    member do 
      post 'like', to: 'likes#create'
    end
  end

   root 'thoughts#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Network</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  

<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid">
		<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header">
			<% if user_signed_in? %>
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<% end %>
			<%= link_to "NetWork", root_path, :class => "navbar-brand" %>
		</div>

		<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse navbar-ex1-collapse">
			<ul class="nav navbar-nav navbar-right">
			  <% if user_signed_in? %>
  				<li><%= link_to "Profile", profiles_show_path(:id => current_user.id) %></li>
  				<li><%= link_to "Feed", root_path %></li>
  				<li><%= link_to "Connect", my_network_show_path %></li>
  				<li><%= link_to 'Sign Out', destroy_user_session_path, :method => :delete %></li>
				<% end %>
			</ul>
		</div><!-- /.navbar-collapse -->
	</div>
</nav>

<div class="container">
  
<!-- FLASH MESSAGES -->

  <div>
  	<% flash.each do |key, value| %>
      	<div>
      		<%= value %>
      	</div>
  	<% end %>
  </div>
  
  <%= yield %>
  
</div>



</body>
</html>